config/routes.rb
Rails.application.routes.draw do
  get 'services/index'
  get 'contact_us/index'
  get 'about_us/index'
  devise_for :users
  resources :parts
  #get 'home/index'
  root 'home#index'

  get 'search', to: "parts#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/part.rb
class Part < ApplicationRecord
	has_one_attached:image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  def search
    @parts = Part.where("part_name LIKE ?", "%"+ params[:q] +"%")
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def part_params
      params.require(:part).permit(:part_name, :car_type, :car_make, :car_model, :part_id, :description, :price, :image)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/about_us/index.html.erb
<h1>About Us</h1>
<br/>

<div>

 <div class="row">
   <div class="col-sm">

	<%= image_tag ("Mechanic at work"), class:"d-block w-100" %>
	<br/>
   </div>

  <div class="col-sm">
    
    <p>
     North Melbourne wreckers is a leading used auto parts seller and wrecking business based in Coburg, Melbourne.
     We are known for selling quality used car parts at a low price. Besides these, we also provide car removal services
     free of cost and we pay good price for cars in Melbourne.
    </p>

    <p>
    Our company is an Australian car wrecking company selling used auto parts in Melbourne. We understand the difficulties 
    of finding perfect car part when the budget is tight. We understand that not everybody can afford to buy original car parts,
    and it is very hard to find the best reconditioned parts. Thats why, we provide best quality reconditioned car parts at a very 
    reasonable affordable price.
    </p>

   </div>
 </div>

</div>

app/views/contact_us/index.html.erb
<h1>Contact Us</h1>
<br/>

<div class="container">
 <div class="rows">

 	<%= image_tag ("Google map view"), class:"d-block w-60" %>

 </div>

 <br/>	

<div class="rows">

 <h2>Address</h2>

 <p>
 	15 Mercier St, Coburg North VIC 3058
 </p> 	

 </div>

 <div class="rows">

 <h2>Phone Us</h2>

 <p>
 	<strong>Call us</strong> on 0421701967
 </p> 	

 </div>		

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'North Coburg Wreckers', root_path, class:"navbar-brand" %>

  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">


    <% if user_signed_in? %>

      <li class="nav-item active">
        <%= link_to 'Parts List', parts_path, class:"nav-link" %>
        
      </li>

      <li class="nav-item">
        <%= link_to 'Add New Part', new_part_path, class:"nav-link" %>
        
      </li>  
    

      <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
        
      </li>  

      <li class="nav-item">
        <%= link_to 'Update User Information', edit_user_registration_path, class:"nav-link" %>
        
      </li>

    <form class="form-inline my-2 my-lg-0" action="/search">
      <input class="form-control mr-sm-2" name="q" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    
    <% else %>

      <li class="nav-item">
        <%= link_to 'About Us', about_us_index_path, class:"nav-link" %>
        
      </li>

      
      <li class="nav-item">
        <%= link_to 'Services', services_index_path, class:"nav-link" %>
        
      </li>

      <li class="nav-item">
        <%= link_to 'Contact Us', contact_us_index_path, class:"nav-link" %>
        
      </li>
    

    <% end %>

    </ul>

    





    
  </div>
</nav>

app/views/home/index.html.erb
<h1>North Coburg Wreckers</h1>
<br/>

<p>
<%= image_tag ("Home"), class:"d-block w-100" %>
</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>North Coburg Wreckers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'home/header'%>
    <div class="container">
      <br/>
    
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    

    <%= yield %>
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/parts/_form.html.erb
<%= form_with(model: part, local: true) do |form| %>
  <% if part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
        <% part.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :part_name %>
    <%= form.text_field :part_name, class:"form-control col-5" %>
  </div>

  <div class="field form-group">
    <%= form.label :car_type %>
    <%= form.text_field :car_type, class:"form-control col-5" %>
  </div>

  <div class="field form-group">
    <%= form.label :car_make %>
    <%= form.text_field :car_make, class:"form-control col-5" %>
  </div>

  <div class="field form-group">
    <%= form.label :car_model %>
    <%= form.text_field :car_model, class:"form-control col-5" %>
  </div>

  <div class="field form-group">
    <%= form.label :part_id %>
    <%= form.text_field :part_id, class:"form-control col-5"%>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control col-5" %>
  </div>

  <div class="field form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class:"form-control col-5" %>
  </div>

  <div class="form-group">
    <% if part.image.attached? %>
    <%= image_tag part.image, style: "width: 200px; display: block" %>
    <% end %>
    

    <%= form.label :image %>
    <%= form.file_field :image, class:"form-control col-5" %>

    
    

    
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/parts/_search_result.erb
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Part name</th>
      <th>Car type</th>
      <th>Car make</th>
      <th>Car model</th>
      <th>Part</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td><%= link_to part.part_name, part %></td>
        <td><%= part.car_type %></td>
        <td><%= part.car_make %></td>
        <td><%= part.car_model %></td>
        <td><%= part.part_id %></td>
        <td><%= part.description %></td>
        <td><%= part.price %></td>
        
        <td><%= link_to 'Update Part', edit_part_path(part), class:"btn btn-outline-primary btn-sm" %></td>
        <td><%= link_to 'Delete', part, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/parts/edit.html.erb
<h1>Update Part</h1>
<br/>
<%= render 'form', part: @part %>
<br/>

<%= link_to 'Show', @part, class:"btn btn-primary" %>
<%= link_to 'Delete', @part, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
<br/><br/>

<%= link_to 'Cancel', parts_path, class:"btn btn-secondary" %>

app/views/parts/index.html.erb
<div class="container">

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Part name</th>
      <th>Car type</th>
      <th>Car make</th>
      <th>Car model</th>
      <th>Part Number</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td><%= link_to part.part_name, part %></td>
        <td><%= part.car_type %></td>
        <td><%= part.car_make %></td>
        <td><%= part.car_model %></td>
        <td><%= part.part_id %></td>
        <td><%= part.description %></td>
        <td><%= part.price %></td>
        
        <td><%= link_to 'Update Part', edit_part_path(part), class:"btn btn-outline-primary btn-sm" %></td>
        <td><%= link_to 'Delete', part, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Part', new_part_path, class:"btn btn-primary" %>
</div>

app/views/parts/new.html.erb
<h1>Add New Part</h1>

<%= render 'form', part: @part %>

<br/>
<%= link_to 'Cancel', parts_path, class:"btn btn-secondary" %>

app/views/parts/search.erb
<h1>Search Results</h1>
<br/>

<%= render 'parts/search_result' %>

<br/>

<%= link_to 'Back', parts_path, class:"btn btn-secondary" %>

app/views/parts/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
  <%= @part.part_name %>
  </h1>
  <p class="lead">
    <%= @part.description %>
  </p>

  <hr class="my-4">
  
    <p>
  <strong>Car type:</strong>
  <%= @part.car_type %>
</p>

<p>
  <strong>Car make:</strong>
  <%= @part.car_make %>
</p>

<p>
  <strong>Car model:</strong>
  <%= @part.car_model %>
</p>

<p>
  <strong>Part:</strong>
  <%= @part.part_id %>
</p>


<p>
  <strong>Price:</strong>
  <%= @part.price %>
</p>

<p>
  
  <%= image_tag @part.image, style: "width: 200px; display: block" %>
</p>

<br/>

<%= link_to 'Update Part', edit_part_path(@part), class:"btn btn-primary" %>
<%= link_to 'Delete', @part, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
<br/><br/> 
<%= link_to 'Back', parts_path, class:"btn btn-secondary" %>

</div>

app/views/services/index.html.erb
<h1>Services</h1>

<div>
<br/>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <%= image_tag ("Car Part"), class:"d-block w-100" %>
	<br/>
    </div>

    <div class="col-sm">

    <h2>Used Parts</h2>
    
      <p>
      We sell used parts for all brands and models. We offer quality reconditioned parts at a very affordable price. When it comes to buy reconditioned car parts, trust is an isuue sometimes, and we recognised that. Thats why, we made trustworthyness our main business principle. You can have piece of mind that, when you buy parts from us, you are getting best possible reconditioned part.	
      </p>
	<br/>
    </div>

</div>

 </div>
<br/><br/>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <h2>Want to Sell your car?</h2>
       <br/>

          <p>
          	Do you have a car you no longer use? Or perhaps, you have got a car which is damaged beyond repair and you want to get rid off it. Then, you are at the right place. We buy damaged used car as well. We help you to get rid of the unwanted car for a very good price. 


          </p>
	     <br/>
	
    </div>

    <div class="col-sm">
    	<br/><br/><br/>

    	<%= image_tag ("Sell your car"), class:"d-block w-100" %>
	     <br/>

   
    </div>

  </div>

</div>

</div>